/**
 * @providesModule CoinActionTypes
 * @flow
 */

export const CHANGE_CURRENCY_TYPE = 'CURRENCY_TYPE';
export const CHANGE_NUMBER_COINS = 'NUMBER_COINS';
export const CHANGE_PERCENTAGE_TIME_PERIOD = 'PERCENTAGE_TIME_PERIOD';
export const GET_COIN_DATA = 'GET_COIN_DATA';
export const GET_USER_COINS = 'GET_USER_COINS';
export const USER_COINS = 'USER_COINS';
export const CALCULATE_PORTFOLIO_VALUE = 'CALCULATE_PORTFOLIO_VALUE';